name: wine-model-name
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: iterative/setup-cml@v1

      - name: Train model
        env:
          MY_PERSONAL_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro

          # Debug: List files in the current directory
          echo "### Files in the current directory after training"
          ls -la
          git fetch --prune
          dvc metrics diff --show-md master > report.md
         
          # Add images to the report using the new syntax
          echo "![By Region](by_region.png)" >> report.md
  

          # Debug: Output the content of report.md
          echo "### Contents of report.md"
          cat report.md

          # Send the report as a comment to the PR
          cml comment create report.md --token $MY_PERSONAL_TOKEN
